package bike_rental.model;

public class AdminUser extends Person {

    private String adminLevel; // values: 'super', 'moderator', 'standard'

    public AdminUser(String userId, String name, String email,
                     String password, String adminLevel) {
        super(userId, name, email, password); // calls Person's constructor
        this.adminLevel = adminLevel;
    }

    public AdminUser() {
        super();
    }

    public String getAdminLevel() {
        return adminLevel;
    }

    public void setAdminLevel(String adminLevel) {
        this.adminLevel = adminLevel;
    }

    @Override
    public String getRole() {
        return "admin";
    }

    public String generateAdminReport() {
        return "Admin Report generated by " + getName()
                + " [Level: " + adminLevel + "]";
    }
}