# src/main/resources/application.properties

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/bike_rental_db
spring.datasource.username=root
spring.datasource.password=TEHANtehan123@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Thymeleaf settings
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Show SQL queries in console (helpful for debugging)
spring.jdbc.template.query-timeout=10
logging.level.org.springframework.jdbc=DEBUG

# Server port
server.port=8080

